### ISSUE TITLE
Custom ClientAppSettings / not using outdated roblox APIs

### ISSUE THREAD

**Issue by prrf** [terminite1/ExclusiveFullscreen#1]
Can you add the ability to use other sources for ClientAppSettings.json or the ability to add extra FastFlags

also you should use `setup.rbxcdn.com/version` instead of `setup.roblox.com/version` as the version.txt hosted on the main roblox domain is old and they ["will likely lock access to it soon."](https://devforum.roblox.com/t/setuprobloxcom-has-an-invalid-certificate/659467)

an even better solution than the one described above is to get the version info from the [ClientSettings API](https://clientsettingscdn.roblox.com/v1/client-version/WindowsPlayer) as they also mention how 'version.txt probably wont be arround forever' but i doubt that version.txt is going away anytime soon so you should be good for now

**Comment by terminite1** [comment]
sure i'll try working on it, but do you have any suggestions as to what fflags i should add?

**Comment by terminite1** [comment]
pls

**Comment by prrf** [comment]
i was on vacation but you could add lighting engine, pause menu version, and AntiAliasing selectors. i dont know the exact fastflags for those so look them up or smthn idk

**Comment by terminite1** [comment]
as discussed over discord, i have updated to the new APIs and will not add new fastflags
